### ISSUE TITLE
M3U Support

### ISSUE THREAD

**Issue by newoski** [libretro/beetle-pcfx-libretro#3]
Hi,

Would it be possible to add m3u support to this core, similar to PlayStation, for multidisc games?

Thanks so much!

**Comment by retro-wertz** [comment]
anyone still needs this? im not entirely sure as how many games actually has 2 or more disks.

**Comment by newoski** [comment]
yes, this would be really fantastic!!!

**Comment by bebess** [comment]
any news ? :)

**Comment by televandalist** [comment]
Also interested in this. Would like to go through Last Imperial Prince at some point :)

**Comment by negativeExponent** [comment]
since most games are Japanese, instead of a flat-out feature request, it would make more sense to at least state which games uses multiple disks and at least do a playthrough and then send in the savefiles and savestates near the area where change of disk is requested. This would make it easier to test than just blindly add untested PR.

**Comment by negativeExponent** [comment]
rejoice, though its just very basic and the disks has to be in the m3u file. no adding of disks supported yet, or other features like disk labels etc like that. not tested on actual multidisk games, only on separate games switching between then and resetting core, or play audio in the bios' cdplayer (upper-left icon)

this is just a baseline implementation, depending on the feedback i may add the rest of the disk interface features, or maybe someone else can do it.
